# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-26 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0002_auto_20161126_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scorername', models.CharField(max_length=160, null=True)),
                ('minute', models.IntegerField(null=True)),
                ('type', models.CharField(max_length=32, null=True)),
                ('scored_against', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='against', to='club.Club')),
                ('scorerclub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forclub', to='club.Club')),
            ],
        ),
    ]
