# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-26 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0002_match'),
        ('match_events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match', to='fixtures.Match'),
        ),
    ]
