# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-26 09:50
from __future__ import unicode_literals

from django.db import models, migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('url', models.CharField(max_length=500)),
            ],
        ),
    ]
