# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-26 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(default='UCD', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
